---
title: "ST5188 PG01 Exploratory Data Analysis"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
#| echo: FALSE
#| include: FALSE

# clear working directory
rm(list = ls())

# source libraries and functions under `Code` files
scripts = list.files("../Code/Preprocessing", full.names = TRUE)

lapply(scripts[c(1, 3:5, 10)], function(file) {
  if (grepl("\\.py$", file)) {
    source_python(file)
    cat("Successfully sourced .py file:", file, "\n")
  } else {
    source(file)
    cat("Successfully sourced .R file:", file, "\n")
  }
})
```

### {.tabset .tabset-fade .tabset-pills}
Let's perform exploratory data analysis on our dataset!

#### Changi
```{r}
#| echo: FALSE
#| include: FALSE

# this section is to pre-process CHANGI data
subzone = "CHANGI"

# extract, impute and combine data from images - swarnali + amira
df_changi <- combine_img(subzone) # takes around 3-4 mins
rownames(df_changi) <- NULL

# aggregate temporally and obtain final data - naomi
long_changi <- st_aggregate(df_changi, subzone)[1]
wide_changi <- st_aggregate(df_changi, subzone)[2]
```

```{r}
#| fig.width: 10
# this section is to do EDA - all


```

#### Jurong East
```{r}
#| echo: FALSE
#| include: FALSE

# this section is to pre-process JURONG data
subzone = "JURONG EAST"

# extract, impute and combine data from images
df_jurongeast <- combine_img(subzone)
rownames(df_jurongeast) <- NULL

# aggregate temporally and obtain final data
final_jurongeast <- st_aggregate(df_jurongeast, subzone)
```

```{r}
#| fig.width: 10

# this section is to do EDA



```


#### Jurong West
```{r}
#| echo: FALSE
#| include: FALSE

# this section is to pre-process JURONG data
subzone = "JURONG WEST"

# extract, impute and combine data from images
df_jurongwest <- combine_img(subzone)

# aggregate temporally and obtain final data
final_jurongwest <- st_aggregate(df_jurongwest, subzone)
```