---
title: "ST5188-working of spTimer"
output: html_document
---

```{r setup, include=FALSE,message=FALSE}

# clear working directory
rm(list = ls())

scripts = list.files("../Code/Preprocessing", full.names = TRUE)

library(spTimer)

#memory.limit(size = 8000)  # Increase memory limit (in MB) In windows


# Load the package
library(ff)

```

Loading the data set: Changi region

```{r}
data<-as.data.frame(read.csv("../Data/Final/final_CHANGI_long.csv"))
data <- na.omit(data)  
head(data)


#Longitude:x
#Latitude:y
#time: period

```

```{r}
# Convert 'period' to a factor variable
data$period <- as.factor(data$period)

# Check the structure again to confirm 'period' is now a factor
str(data)
# 
 model_formula <- avg_LST ~ x + y   # Example formula, adjust as needed

```

```{r}
#trying for a small dataset

# Check for missing values in coordinates
sum(is.na(data$x))
sum(is.na(data$y))

# Filter out rows with missing coordinates
data <- data[!is.na(data$x) & !is.na(data$y), ]

# Subsampling:
subsampled_data <- data[seq(1, nrow(data), by = 100), ]

#remove duplicates
subsampled_data <- data[!duplicated(subsampled_data[, c("x", "y")]), ]

# Convert 'period' to a factor variable
subsampled_data$period <- as.factor(subsampled_data$period)

# Check the structure again to confirm 'period' is now a factor
str(subsampled_data)
```

```{r}
# Specify the formula for the model
formula <- avg_LST ~ 1 + period

coords <- as.matrix(data[, c("x", "y")])  # Create matrix of coordinates

# Define priors for the GP model
priors <- spTimer::spT.priors(
  model = "GP",
  inv.var.prior = spTimer::Gamm(2, 2),
  beta.prior = spTimer::Norm(0, 10^2)
)

```

```{r}
#Attempt in fitting 1

subsampled_coords <- as.matrix(subsampled_data[, c("x", "y")])

dim(subsampled_data)  # Ensure data is not empty
str(subsampled_data)  # Confirm variable types

# Fit the hierarchical Bayesian model using spTimer
model <- spTimer::spT.Gibbs(
  formula = formula,
  data = subsampled_data,
  coords=subsampled_coords,  # Ensure these match your dataset
  model = "GP",  # Gaussian Process model
  priors = priors,  # Set priors
  nItr = 500,   # Lower iterations for quick test
  nBurn = 200,  # Lower burn-in for quick test
  # nThin = 10,   # Thinning to speed up convergence
  cov.fnc="exponential"
)



# Check model summary
summary(model)
```

```{r}
#attempt inn fitting option 2

# Define priors for the GP model
priors <- spTimer::spT.priors(
    model = "GP",
    inv.var.prior = matrix(c(2, 2), nrow = 1, ncol = 2, byrow = TRUE),  # Inverse Gamma prior
    beta.prior = matrix(c(0, 100), nrow = 1, ncol = 2, byrow = TRUE)   # Normal prior
)

# Fit the hierarchical Bayesian model using spTimer
model <- spTimer::spT.Gibbs(
  formula = formula,
  data = subsampled_data,
  coords = as.matrix(data[, c("x", "y")]) ,  
  model = "GP",  
  priors = priors,  
  nItr = 2000,  # Increase for better results
  nBurn = 1000,
  cov.fnc="gaussian"
)
```
